export const gears = [
  {
    "name": "Bâton de Boisaille",
    "level": 9,
    "type": "Bâton",
    "imgUrl": "https://s.ankama.com/www/static.ankama.com/dofus/www/game/items/200/4001.png",
    "description": "Bâton de simple facture, il ne fera pas de votre héros une légende.",
    "sold": 0,
    "currentPrice": 1699,
    "isWished": false,
    "isWanted": false,
    "toBeCrafted": 0,
    "recipe": [{
      "_id": "62a9d91307a447b19d82774f",
      "name": "Os de Chafer",
      "level": 5,
      "type": "Os",
      "imgUrl": "https://s.ankama.com/www/static.ankama.com/dofus/www/game/items/200/47015.png",
      "description": "Cet os est presque incassable, mais il devient tout mou au contact de l'eau, ce qui facilite son utilisation par les alchimistes.",
      "sold": 0,
      "currentPrice": 23,
      "isWanted": false,
      "__v": 0,
      "soldByHundred": 0,
      "soldByTen": 0,
      "isWantedForHundred": false,
      "isWantedForTen": false,
      "timesRequiredInRecipes": 82,
      "quantity": 3,
      "isEmpty": false
    },
      {
      "name": "Feu Intérieur",
      "level": 1,
      "type": "Ressources diverses",
      "imgUrl": "https://s.ankama.com/www/static.ankama.com/dofus/www/game/items/200/164067.png",
      "description": "Après des années de méditation, vous serez peut-être capable de révéler votre feu intérieur. Si vous n’avez pas envie d’attendre, vous pouvez tout aussi bien martyriser des Feux spirituels.",
      "sold": 0,
      "currentPrice": 0,
      "isWanted": false,
      "isWantedForHundred": false,
      "isWantedForTen": false,
      "soldByHundred": 0,
      "soldByTen": 0,
      "timesRequiredInRecipes": 50,
      "quantity": 3,
      "isEmpty": true
    }],
    "craftingPrice": 69,
    "isInMarket": false,
    "ratio": 24.6231884057971,
    "isInInventory": false,
    "lastPriceUpdatedAt": "2022-08-21T10:46:57.725Z",
    "isOnWaitingList": 0,
    "onWishList": 0
  }, {
    "name": "Marteau de Raclage",
    "level": 15,
    "type": "Marteau",
    "imgUrl": "https://s.ankama.com/www/static.ankama.com/dofus/www/game/items/200/7002.png",
    "description": "Un marteau bien travaillé, intéressant pour les novices.",
    "sold": 0,
    "currentPrice": 3998,
    "isWished": false,
    "isWanted": false,
    "toBeCrafted": 0,
    "recipe": [{
      "name": "Sourcil de Moskito",
      "level": 13,
      "type": "Poil",
      "imgUrl": "https://s.ankama.com/www/static.ankama.com/dofus/www/game/items/200/15044.png",
      "description": "Le Moskito dispose de longs et fins sourcils qui mettent en valeur son regard de grand charmeur.",
      "sold": 0,
      "currentPrice": 24,
      "isWanted": false,
      "soldByHundred": 0,
      "soldByTen": 0,
      "isWantedForHundred": false,
      "isWantedForTen": false,
      "timesRequiredInRecipes": 56,
      "quantity": 1,
      "isEmpty": false
    },
      {
      "name": "Plume de Piou Vert",
      "level": 13,
      "type": "Plume",
      "imgUrl": "https://s.ankama.com/www/static.ankama.com/dofus/www/game/items/200/53116.png",
      "description": "Cette petite plume de Piou a été directement arrachée du derrière d'un pauvre Piou qui n'avait rien demandé.",
      "sold": 0,
      "currentPrice": 67,
      "isWanted": false,
      "isWantedForHundred": false,
      "isWantedForTen": false,
      "soldByHundred": 0,
      "soldByTen": 0,
      "timesRequiredInRecipes": 56,
      "quantity": 3,
      "isEmpty": false
    }],
    "craftingPrice": 225,
    "isInMarket": true,
    "ratio": 17.76888888888889,
    "isInInventory": true,
    "lastPriceUpdatedAt": "2022-08-26T08:00:46.335Z",
    "isOnWaitingList": 0,
    "onWishList": 0
  }
]